print("Aaron Zhang")
print("I am a sophomore, but first year in computer science major")
print("I come from Shanghai, China")
print("I am the only child in my family")
print("I prefer to do sports and read various books in my free time")
input("press <enter>")
