junit5:
	javac -cp .:./classes/:junit-platform-console-standalone-1.3.2.jar *.java
	java -jar junit-platform-console-standalone-1.3.2.jar -f TestDS_My 

all:
	javac -cp .:./classes/:junit-platform-console-standalone-1.3.2.jar *.java
	java -jar junit-platform-console-standalone-1.3.2.jar -f TestDS_Gautham
	java -jar junit-platform-console-standalone-1.3.2.jar -f TestDS_Katie
	java -jar junit-platform-console-standalone-1.3.2.jar -f TestDS_Niveditha
	java -jar junit-platform-console-standalone-1.3.2.jar -f TestDS_Roshan
	java -jar junit-platform-console-standalone-1.3.2.jar -f TestDS_Varun
	java -jar junit-platform-console-standalone-1.3.2.jar -f TestDS_Vibhor

